package com.betfair.sim.service;

import com.betfair.sim.model.RecentEventEntry;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDate;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;

@Service
public class RecentEventsService {
  private static final DateTimeFormatter RECENT_FILE_DATE = DateTimeFormatter.BASIC_ISO_DATE;
  private static final DateTimeFormatter MATCH_DATE_FORMAT = DateTimeFormatter.ofPattern("dd.MM.yyyy");

  private final ObjectMapper objectMapper;
  private final JdbcTemplate jdbcTemplate;
  private final Path recentDir;

  public RecentEventsService(
      ObjectMapper objectMapper,
      JdbcTemplate jdbcTemplate,
      @Value("${betfair.followed-games.dir:backend/data}") String baseDir) {
    this.objectMapper = objectMapper;
    this.jdbcTemplate = jdbcTemplate;
    this.recentDir = FollowedGamesPathResolver.resolve(baseDir).resolve("recent");
    initSchema();
  }

  public List<RecentEventEntry> loadByDate(String date) {
    LocalDate resolvedDate =
        date == null || date.isBlank() ? LocalDate.now(ZoneOffset.UTC) : LocalDate.parse(date);
    Path sourceFile = recentDir.resolve(resolvedDate.format(RECENT_FILE_DATE) + ".txt");
    if (Files.exists(sourceFile)) {
      List<RawRecentEvent> rows = parseFile(sourceFile, resolvedDate);
      replaceRowsForDate(resolvedDate, sourceFile, rows);
    }
    return fetchRowsForDate(resolvedDate);
  }

  private void initSchema() {
    jdbcTemplate.execute(
        "CREATE TABLE IF NOT EXISTS recent_events ("
            + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            + "main_id VARCHAR(64) NOT NULL,"
            + "match_date DATE NOT NULL,"
            + "league_name VARCHAR(255),"
            + "home_team VARCHAR(255),"
            + "away_team VARCHAR(255),"
            + "ht_home_goals INT,"
            + "ht_away_goals INT,"
            + "ft_home_goals INT,"
            + "ft_away_goals INT,"
            + "status VARCHAR(32),"
            + "source_file VARCHAR(512),"
            + "updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,"
            + "UNIQUE(main_id, match_date)"
            + ")");
  }

  private List<RawRecentEvent> parseFile(Path sourceFile, LocalDate fallbackDate) {
    JsonNode root;
    try {
      root = objectMapper.readTree(Files.newBufferedReader(sourceFile));
    } catch (IOException ex) {
      throw new UncheckedIOException("Failed to parse recent file: " + sourceFile, ex);
    }

    List<RawRecentEvent> rows = new ArrayList<>();
    root.fields()
        .forEachRemaining(
            rootField -> {
              JsonNode leagues = rootField.getValue().path("league");
              if (!leagues.isArray()) {
                return;
              }
              for (JsonNode leagueNode : leagues) {
                String leagueName = textOrEmpty(leagueNode.path("name"));
                JsonNode matches = leagueNode.path("match");
                if (!matches.isArray()) {
                  continue;
                }
                for (JsonNode matchNode : matches) {
                  String mainId = textOrEmpty(matchNode.path("main_id"));
                  if (mainId.isBlank()) {
                    continue;
                  }
                  LocalDate matchDate =
                      parseMatchDate(textOrEmpty(matchNode.path("date")), fallbackDate);
                  rows.add(
                      new RawRecentEvent(
                          mainId,
                          matchDate,
                          leagueName,
                          textOrEmpty(matchNode.path("home").path("name")),
                          textOrEmpty(matchNode.path("away").path("name")),
                          intOrNull(matchNode.path("ht").path("home_goals")),
                          intOrNull(matchNode.path("ht").path("away_goals")),
                          intOrNull(matchNode.path("ft").path("home_goals")),
                          intOrNull(matchNode.path("ft").path("away_goals")),
                          textOrEmpty(matchNode.path("status"))));
                }
              }
            });
    return rows;
  }

  private void replaceRowsForDate(LocalDate date, Path sourceFile, List<RawRecentEvent> rows) {
    if (rows.isEmpty()) {
      return;
    }

    Map<String, RawRecentEvent> uniqueRows = new LinkedHashMap<>();
    for (RawRecentEvent row : rows) {
      uniqueRows.put(row.mainId() + "|" + row.matchDate(), row);
    }
    List<RawRecentEvent> dedupedRows = new ArrayList<>(uniqueRows.values());

    jdbcTemplate.batchUpdate(
        "MERGE INTO recent_events ("
            + "main_id, match_date, league_name, home_team, away_team, "
            + "ht_home_goals, ht_away_goals, ft_home_goals, ft_away_goals, status, source_file, updated_at"
            + ") KEY(main_id, match_date) "
            + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)",
        dedupedRows,
        dedupedRows.size(),
        (ps, row) -> {
          ps.setString(1, row.mainId());
          ps.setObject(2, row.matchDate());
          ps.setString(3, row.leagueName());
          ps.setString(4, row.homeTeam());
          ps.setString(5, row.awayTeam());
          if (row.htHomeGoals() == null) {
            ps.setNull(6, java.sql.Types.INTEGER);
          } else {
            ps.setInt(6, row.htHomeGoals());
          }
          if (row.htAwayGoals() == null) {
            ps.setNull(7, java.sql.Types.INTEGER);
          } else {
            ps.setInt(7, row.htAwayGoals());
          }
          if (row.ftHomeGoals() == null) {
            ps.setNull(8, java.sql.Types.INTEGER);
          } else {
            ps.setInt(8, row.ftHomeGoals());
          }
          if (row.ftAwayGoals() == null) {
            ps.setNull(9, java.sql.Types.INTEGER);
          } else {
            ps.setInt(9, row.ftAwayGoals());
          }
          ps.setString(10, row.status());
          ps.setString(11, sourceFile.toString());
        });
  }

  private List<RecentEventEntry> fetchRowsForDate(LocalDate date) {
    return jdbcTemplate.query(
        "SELECT main_id, match_date, league_name, home_team, away_team, "
            + "ht_home_goals, ht_away_goals, ft_home_goals, ft_away_goals, status "
            + "FROM recent_events WHERE match_date = ? "
            + "ORDER BY league_name ASC, home_team ASC, away_team ASC",
        (rs, rowNum) ->
            new RecentEventEntry(
                rs.getString("main_id"),
                rs.getObject("match_date", LocalDate.class) == null
                    ? ""
                    : rs.getObject("match_date", LocalDate.class).toString(),
                rs.getString("league_name"),
                rs.getString("home_team"),
                rs.getString("away_team"),
                rs.getObject("ht_home_goals") == null ? null : rs.getInt("ht_home_goals"),
                rs.getObject("ht_away_goals") == null ? null : rs.getInt("ht_away_goals"),
                rs.getObject("ft_home_goals") == null ? null : rs.getInt("ft_home_goals"),
                rs.getObject("ft_away_goals") == null ? null : rs.getInt("ft_away_goals"),
                rs.getString("status")),
        date);
  }

  private static LocalDate parseMatchDate(String value, LocalDate fallbackDate) {
    if (value == null || value.isBlank()) {
      return fallbackDate;
    }
    try {
      return LocalDate.parse(value, MATCH_DATE_FORMAT);
    } catch (DateTimeParseException ex) {
      return fallbackDate;
    }
  }

  private static String textOrEmpty(JsonNode node) {
    if (node == null || node.isMissingNode() || node.isNull()) {
      return "";
    }
    return node.asText("");
  }

  private static Integer intOrNull(JsonNode node) {
    if (node == null || node.isMissingNode() || node.isNull()) {
      return null;
    }
    String text = node.asText("").trim();
    if (text.isBlank()) {
      return null;
    }
    try {
      return Integer.parseInt(text);
    } catch (NumberFormatException ex) {
      return null;
    }
  }

  private record RawRecentEvent(
      String mainId,
      LocalDate matchDate,
      String leagueName,
      String homeTeam,
      String awayTeam,
      Integer htHomeGoals,
      Integer htAwayGoals,
      Integer ftHomeGoals,
      Integer ftAwayGoals,
      String status) {}
}
