CREATE TABLE IF NOT EXISTS recent_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  main_id VARCHAR(64) NOT NULL,
  match_date DATE NOT NULL,
  league_name VARCHAR(255),
  home_team VARCHAR(255),
  away_team VARCHAR(255),
  ht_home_goals INT,
  ht_away_goals INT,
  ft_home_goals INT,
  ft_away_goals INT,
  status VARCHAR(32),
  source_file VARCHAR(512),
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_recent_events_main_date UNIQUE (main_id, match_date)
);

CREATE TABLE IF NOT EXISTS refdata_statpal_betfair (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_date DATE NOT NULL,
  statpal_main_id VARCHAR(64) NOT NULL,
  statpal_home_team VARCHAR(255),
  statpal_away_team VARCHAR(255),
  betfair_event_id VARCHAR(64) NOT NULL,
  betfair_home_team VARCHAR(255),
  betfair_away_team VARCHAR(255),
  confidence_score DOUBLE PRECISION,
  mapping_source VARCHAR(32) NOT NULL DEFAULT 'manual',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_refdata_statpal_main UNIQUE (match_date, statpal_main_id),
  CONSTRAINT uq_refdata_betfair_event UNIQUE (match_date, betfair_event_id)
);

CREATE TABLE IF NOT EXISTS refdata_statpal_betfair_team (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  statpal_team_name VARCHAR(255) NOT NULL,
  betfair_team_name VARCHAR(255) NOT NULL,
  normalized_statpal_team VARCHAR(255) NOT NULL,
  normalized_betfair_team VARCHAR(255) NOT NULL,
  mapping_source VARCHAR(32) NOT NULL DEFAULT 'manual',
  confidence_score DOUBLE PRECISION,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_refdata_team_names UNIQUE (normalized_statpal_team, normalized_betfair_team)
);

CREATE TABLE IF NOT EXISTS strategy_balances (
  strategy_id VARCHAR(64) PRIMARY KEY,
  strategy_name VARCHAR(128),
  current_balance DOUBLE PRECISION NOT NULL DEFAULT 0,
  total_profit DOUBLE PRECISION NOT NULL DEFAULT 0,
  settled_bets INT NOT NULL DEFAULT 0,
  wins INT NOT NULL DEFAULT 0,
  losses INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS overunder_15_stats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  strategy_id VARCHAR(64) NOT NULL,
  event_id VARCHAR(64) NOT NULL,
  market_id VARCHAR(64),
  home_team VARCHAR(255),
  away_team VARCHAR(255),
  league VARCHAR(255),
  placed_at_minute VARCHAR(32),
  odds DOUBLE PRECISION NOT NULL,
  stake DOUBLE PRECISION NOT NULL,
  state VARCHAR(16) NOT NULL,
  profit DOUBLE PRECISION NOT NULL DEFAULT 0,
  latest_score VARCHAR(32),
  latest_minute VARCHAR(32),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  settled_at TIMESTAMP,
  CONSTRAINT uq_overunder_strategy_event UNIQUE (strategy_id, event_id)
);

CREATE TABLE IF NOT EXISTS overunder_strategy_balances (
  strategy_id VARCHAR(64) PRIMARY KEY,
  current_balance DOUBLE PRECISION NOT NULL,
  settled_profit DOUBLE PRECISION NOT NULL,
  open_bets INT NOT NULL,
  finished_bets INT NOT NULL,
  wins INT NOT NULL,
  losses INT NOT NULL,
  won_value DOUBLE PRECISION NOT NULL,
  lost_value DOUBLE PRECISION NOT NULL,
  stake DOUBLE PRECISION NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_recent_events_match_date ON recent_events(match_date);
CREATE INDEX IF NOT EXISTS idx_refdata_match_date ON refdata_statpal_betfair(match_date);
CREATE INDEX IF NOT EXISTS idx_overunder_state ON overunder_15_stats(state);
CREATE INDEX IF NOT EXISTS idx_overunder_updated_at ON overunder_15_stats(updated_at);
